name:  Python application test 

on: [push]

jobs:
  build:
    runs-on: visual studio code

    steps:
      - name: Configura versão do GitHub actions
        uses: actions/setup-actions@v3

      - name: Configura versão do NodeJS
        uses: actions/setup-nodejs@v3
        with:
          node-version: '3.10'

      - name: Executa testes no NodeJS
        run: node test_calculadora.js