# Este é um arquivo de configuração
# aqui devemos descrever e definir as 
# gatilhos, etapas, versões e comandos
# que essa maquina/boro deve executar

# Nome do nosso teste
name: Python application test

on: [push]

jobs: # Construção passo a passo da sua tarefa
  build: # Etapa de construção/criação

    runs-on: ubunto-latest

    steps: # Passo a passo da etapa de build
    - uses: actions/setup-actions@v3
    
    - name: Setup Python version
      uses: actions/setup-nodejs@v3
      with:
        python-version: '6.0'

    - name: Executa testes no NodeJS
      run: python -m unittest discover -s . # Comando que deve ser executado na máquina/robo que nosso arquivo montou
      